Repository energyquantified/eq-python-client, pull requests merged in 2023-10, with the labels that each got.

#70 Unit Parameter
  docs/userguide/periods.rst
  docs/userguide/terminology.rst
  docs/userguide/timeseries.rst
  energyquantified/api/instances.py
  energyquantified/api/ohlc.py
  energyquantified/api/period_instances.py
  energyquantified/api/periods.py
  energyquantified/api/srmc.py
  energyquantified/api/timeseries.py
  energyquantified/data/base.py
  energyquantified/data/ohlc.py
  energyquantified/data/periodseries.py
  energyquantified/data/srmc.py
  energyquantified/data/timeseries.py
  energyquantified/parser/ohlc.py
  energyquantified/parser/periodseries.py
  energyquantified/parser/srmc.py
  energyquantified/parser/timeseries.py
Labels: documentation, enhancement

#88 Minor rewording in documentation
  docs/userguide/periods.rst
  docs/userguide/timeseries.rst
Labels: documentation

#82 #81 Add `modified-at-latest` parameter to `eq.instances.relative()`
  CHANGELOG.rst
  energyquantified/api/instances.py
Labels: documentation, enhancement

#89 #84 Add Relative Period Instances
  CHANGELOG.rst
  docs/userguide/period-instances.rst
  energyquantified/api/period_instances.py
Labels: documentation, enhancement

#95 #43 Remove Place.area
  CHANGELOG.rst
  energyquantified/metadata/place.py
  energyquantified/parser/metadata.py
Labels: documentation, enhancement

#94 #90 Remove limitation of parameters for relativ instances
  CHANGELOG.rst
  energyquantified/api/instances.py
Labels: bug

#87 Implement absolute forecast for instances #77
  CHANGELOG.rst
  docs/reference/packages.rst
  docs/reference/reference.rst
  docs/userguide/instances.rst
  energyquantified/api/instances.py
  energyquantified/data/__init__.py
  energyquantified/data/absolute.py
  energyquantified/metadata/options.py
  energyquantified/parser/absolute.py
Labels: documentation, enhancement

#98 #97 Add filter option on curve type for curve search
  CHANGELOG.rst
  docs/userguide/metadata.rst
  energyquantified/api/base.py
  energyquantified/api/metadata.py
  examples/forecasts.py
  examples/search.py
  examples/timeseries.py
Labels: documentation, enhancement

#92 #61 Add subscription information to curve
  CHANGELOG.rst
  README.md
  docs/index.rst
  docs/intro/quickstart.rst
  docs/reference/packages.rst
  docs/reference/reference.rst
  docs/userguide/metadata.rst
  docs/userguide/ohlc.rst
  docs/userguide/periods.rst
  docs/userguide/srmc.rst
  docs/userguide/terminology.rst
  docs/userguide/timeseries.rst
  energyquantified/api/base.py
  energyquantified/metadata/__init__.py
  energyquantified/metadata/curve.py
  energyquantified/metadata/subscription.py
  energyquantified/parser/metadata.py
Labels: documentation, enhancement

#96 #93 Add `UserAPI` and `eq.user.user()`
  CHANGELOG.rst
  docs/reference/packages.rst
  docs/reference/reference.rst
  docs/userguide/auth.rst
  energyquantified/api/__init__.py
  energyquantified/api/user.py
  energyquantified/base.py
  energyquantified/parser/user.py
  energyquantified/user/__init__.py
  energyquantified/user/user.py
Labels: documentation, enhancement

#102 Bugfix empty push feed #101
  CHANGELOG.rst
  energyquantified/api/events.py
  energyquantified/parser/metadata.py
Labels: bug
